name: firebase_otp_blood_bank
description: "A project for observing firebase OTP."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/main_screen_donor.jpg
    - assets/blood_donation.png
    - assets/blood_donor.png
